### ISSUE TITLE
.env file in the project's repo

### ISSUE THREAD

**Issue by Karyum** [webAhead1/onShop#2]
the .env file is supposed to be a secret file, a file which contains settings for an environment but also sensitive details (in the future it might contain passwords and access to APIs which cost money)

to hide it you might need to do the following:
 - Copy the contents of the file
 - Delete the file
 - git add & commit the file change
 - then add the file to the `.gitignore` file

**Comment by Karyum** [comment]
also the templates file location feels incorrect, it's not a public file (a public file is a file which would be sent to the user's browser, the entire file) it's backend only file.

you should move it to the root folder of the project

**Comment by Peculiar-codes** [comment]
> the .env file is supposed to be a secret file, a file which contains settings for an environment but also sensitive details (in the future it might contain passwords and access to APIs which cost money)
> 
> to hide it you might need to do the following:
> 
> * Copy the contents of the file
> * Delete the file
> * git add & commit the file change
> * then add the file to the `.gitignore` file

Already submitted a pull request
