### ISSUE TITLE
sql injection!

### ISSUE THREAD

**Issue by Karyum** [webAhead1/onShop#3]
https://github.com/webAhead1/onShop/blob/master/server.js#L73

This is very dangerous because it's prone to an sql injection, I'll give an example of what is the problem.

[In the following query](https://github.com/webAhead1/onShop/blob/master/server.js#L73) you are a taking an email that a user has written down and adding it to the db, but what if the user is a hacker that instead of writing a valid email wrote the following `1; DROP DATABASE; --`.   the `1;` is to stop the current command and write a new one, the new command `DROP DATABASE;` (this is not the correct syntax but you get the point) would delete the database and all of our tables, and then the `--` would comment out the rest of the query.

refer to this workshop on how to fix this https://github.com/WebAhead/learn-node-postgres#sql-injection

**Comment by abdallah0100** [comment]
Fixed by changing the type of the form to email
